Repository meltano/handbook, pull requests merged in 2022-10, with the labels that each got.

#346 Create new page for Trustmary
  src/_company/tech-stack/_trustmary/index.md
Labels: mktgops::uat, p1-mktgops

#351 Update HubSpot
  src/_company/tech-stack/hubspot/index.md
Labels: mktgops::wip, p1-mktgops

#354 Add seamless.ai to tech stack
  src/_company/tech-stack.md
Labels: mktgops::wip, p1-mktgops

#353 Add seamless.ai directory and file
  src/_company/tech-stack/seamlessai/index.md
Labels: mktgops::wip, p1-mktgops

#355 Update YouTube guidelines
  src/_marketing/content.md
Labels: Documentation, marketing, content
